-- MySQL Script generated by MySQL Workbench
-- Wed Dec 27 14:04:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projectdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `projectdb` ;

-- -----------------------------------------------------
-- Table `projectdb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`employee` (
  `employeeId` INT NOT NULL,
  `employeeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employeeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`issuetype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`issuetype` (
  `issueClass` VARCHAR(45) NOT NULL,
  `issueClassName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`issueClass`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`issuefile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`issuefile` (
  `issueFileId` VARCHAR(45) NOT NULL,
  `issueFileName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`issueFileId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`project` (
  `projectId` VARCHAR(45) NOT NULL,
  `projectName` VARCHAR(45) NOT NULL,
  `projectContent` VARCHAR(255) NOT NULL,
  `projectStartDate` DATE NOT NULL,
  `projectEndDate` DATE NOT NULL,
  `projectOwner` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`projectId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`issue` (
  `projectId` VARCHAR(45) NOT NULL,
  `issueId` INT NOT NULL,
  `issueClass` VARCHAR(45) NOT NULL,
  `issueName` VARCHAR(45) NOT NULL,
  `issueContent` VARCHAR(255) NOT NULL,
  `issueFileId` VARCHAR(45) NOT NULL,
  `issueStatus` INT NOT NULL,
  `issueDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`issueId`, `issueFileId`),
  INDEX `fk_issue_project_id_idx` (`projectId` ASC) ,
  INDEX `fk_issue_issue_class_idx` (`issueClass` ASC) ,
  INDEX `fk_issue_issue_file_id_idx` (`issueFileId` ASC) ,
  CONSTRAINT `fk_issue_issue_class`
    FOREIGN KEY (`issueClass`)
    REFERENCES `projectdb`.`issuetype` (`issueClass`),
  CONSTRAINT `fk_issue_issue_file_id`
    FOREIGN KEY (`issueFileId`)
    REFERENCES `projectdb`.`issuefile` (`issueFileId`),
  CONSTRAINT `fk_issue_project_id`
    FOREIGN KEY (`projectId`)
    REFERENCES `projectdb`.`project` (`projectId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`projectmember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`projectmember` (
  `projectId` VARCHAR(45) NOT NULL,
  `employeeId` INT NOT NULL,
  PRIMARY KEY (`projectId`, `employeeId`),
  INDEX `fk_pm_employee_id_idx` (`employeeId` ASC) ,
  CONSTRAINT `fk_pm_employee_id`
    FOREIGN KEY (`employeeId`)
    REFERENCES `projectdb`.`employee` (`employeeId`),
  CONSTRAINT `fk_pm_project_id`
    FOREIGN KEY (`projectId`)
    REFERENCES `projectdb`.`project` (`projectId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`schedule` (
  `scheduleId` VARCHAR(45) NOT NULL,
  `purchaseStartDate` DATE NOT NULL,
  `purchaseEndDate` DATE NOT NULL,
  `executionStartDate` DATE NOT NULL,
  `executionEndDate` DATE NOT NULL,
  `checkandacceptStartDate` DATE NOT NULL,
  `checkandacceptEndDate` DATE NOT NULL,
  `paymentStartDate` DATE NOT NULL,
  `paymentEndDate` DATE NOT NULL,
  `projectId` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`scheduleId`),
  INDEX `fk_schedule_project_id_idx` (`projectId` ASC) ,
  CONSTRAINT `fk_schedule_project_id`
    FOREIGN KEY (`projectId`)
    REFERENCES `projectdb`.`project` (`projectId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;